before_script:
  - mkdir build && cd build
  - pacman -Suy --noconfirm && pacman -S --noconfirm cmake make gcc clang

.script: &compile_and_test
  script:
    - CXX=clang++ cmake ..
    - make
    - ./tests/utility_fuzzer_test -max_total_time=60

arch:
  image: "archlinux/base"
  <<: *compile_and_test

